apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongo-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{.Release.name}}-mongo-efs-sc
  resources:
    requests:
      storage: 5Gi