apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
     {{- template "labels" . }}
spec:
  selector:
    instance: {{ .Release.Name }}-pod-backend
  ports:
    - port: 5000
      targetPort: 5000
