apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-service
  labels:
    {{- template "labels" . }}
spec:
  selector:
    instance: {{ .Release.Name }}-pod-mongo
  ports:
  - port: 27017
    targetPort: 27017
