apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-connector-list-namespaces
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-connector-list-namespaces-binding
subjects:
  - kind: User
    name: arn:aws:iam::665727843763:root
roleRef:
  kind: ClusterRole
  name: eks-connector-list-namespaces
  apiGroup: rbac.authorization.k8s.io

